<?xml version="1.0"?>
<package format="3">
  <name>agrover_ros</name>
  <version>1.0.0</version>
  <description>AGROVER MR 25.26 — Nœud ROS2 principal (OpenCR + odométrie + Nav2)</description>

  <maintainer email="rover@agrover.local">AGROVER Team JUNIA HEI4</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <!-- Navigation -->
  <depend>nav2_bringup</depend>
  <depend>slam_toolbox</depend>
  <depend>twist_mux</depend>

  <!-- LiDAR -->
  <depend>rplidar_ros</depend>

  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
